spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/firsttask
    username: Adil
    password: adil
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
