spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/firsttask
    username: Adil
    password: adil
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

security:
  jwt:
    secret: "l9KkXr8y0vZ2D0m0jzQ3rC2o6Jb1O8SxYwG6QyqvJmA="
    expiration-minutes: 15
  bruteForce:
    maxAttempts: 3
    lockMinutes: 5