spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/firsttask
    username: Adil
    password: adil
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

security:
  jwt:
    secret: "l9KkXr8y0vZ2D0m0jzQ3rC2o6Jb1O8SxYwG6QyqvJmA="
    expiration-minutes: 15
  bruteForce:
    maxAttempts: 3
    lockMinutes: 5

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

service-auth:
  shared-secret: "T2V2V1d3ZHNzRjZHa2hsM3Q1Ym13SldoWVRnNGRtQWJUV1lXbG5uUnJzSjhRMzFhQzJkNHd5YUtsc1FqVFRoNlNyYw=="
  issuer: "firsttask"
  audience: "workload-service"
  ttl-minutes: 15

app:
  activemq:
    broker-url: tcp://localhost:61616